import { GitHubBanner } from "@refinedev/core";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import RefineWrapper from "@components/refine-wrapper";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body>
        <Suspense>
          <GitHubBanner />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
